name: Publish to NPM + Create GitHub Release

on:
  push:
    tags:
      - 'v*'

env:
  NODE_VER: '23.7.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VER }}
      - run: npm install
      - run: npm run build
      # - run: npm test

      # Upload only the required files (dist/, README.md, package.json)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-package
          path: |
            dist/
            README.md
            package.json
            NOTICE
            LICENSE

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VER }}
          registry-url: https://registry.npmjs.org/

      # Download the build artifact (only contains required files)
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: npm-package

      # Publish package to NPM
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

  publish-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for GitHub release

    steps:
      - uses: actions/checkout@v4

      # Download the build artifact (already filtered)
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: npm-package

      # Create GitHub Release (no need to specify files again)
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          files: npm-package/**  # Uploads everything in the artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
